'use strict';
// The CUDA stack limit fitted to the kernels a process takes (native/cudadrv.h ptxStack / fitStack / fitKernel; the
// n3-ctx-stack-fit branch, 2026-09-29). The driver reserves CU_LIMIT_STACK_SIZE for every thread the GPU can hold at
// once (x SMs x threads per SM) in every context: main's fixed 8 KB was 1.8 GB per eegpu process on an A100. The fit
// sets it to each kernel's local size where the PTX's stack is bounded (no recursion, no indirect call) and keeps
// main's 8 KB where it is not.
//   CPU (the tool's `stackscan`, no driver): hand-made PTX modules: a call chain's depots summed, recursion, mutual
//   recursion, an indirect call (.callprototype / a register callee), a callee without a body and a module without a
//   kernel all not bounded, a declaration before its body; and the real modules next to the tool (every kernel, bounded).
//   --gpu: `info` fitted (the limit covers every kernel taken, and is below 8 KB where they all are), EEAT_GPU_STACK=8192
//   = main's fixed limit, an explore with the fit gives the same events as with EEAT_GPU_STACK=8192 and the driver
//   raised no limit past the fit (stackNow = stackBytes), a roll process fits its own kernels only (less than explore's).
//   node test/ctxstack.js [--tool=<eegpu>] [--ptxdir=<dir>] [--gpu]
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');
const C = require('../src/common.js');
const E = C.E;
const G = require('../src/gpu.js');
const EL = require('../src/eelvl.js');
const RF = require('../src/reach.js');
const ED = require('../src/editor.js');

const args = C.parseArgs(process.argv.slice(2));
const TOOL = args.tool ? path.resolve(args.tool) : G.nativeTool();
if (!TOOL) { console.log('the native tool is missing: node tools/build-native.js'); process.exit(2); }
const PTXDIR = args.ptxdir ? path.resolve(args.ptxdir) : path.dirname(TOOL);
const TMP = fs.mkdtempSync(path.join(os.tmpdir(), 'eegpu-stack-'));
let pass = 0, fail = 0;
function check(name, ok, detail) {
	if (ok) pass++; else fail++;
	console.log(`  ${ok ? 'ok  ' : 'FAIL'} ${name}${detail ? `: ${detail}` : ''}`);
}
function tool(a, env, input) {
	const r = spawnSync(TOOL, a, { input, encoding: 'utf8', maxBuffer: 1 << 28, timeout: 180e3, windowsHide: true, env: Object.assign({}, process.env, env || {}) });
	const lines = String(r.stdout || '').split('\n').filter((l) => l.startsWith('{')).map((l) => { try { return JSON.parse(l); } catch (e) { return {}; } });
	return { code: r.status, lines, err: String(r.stderr || '').trim().split('\n').pop() };
}
function scan(text) {
	const f = path.join(TMP, `m${Math.random().toString(36).slice(2)}.ptx`);
	fs.writeFileSync(f, text);
	const r = tool(['stackscan', f]);
	return r.lines[0] || { error: r.err };
}

// ---- hand-made PTX (the shapes NVRTC writes: headers at depth 0, depots as .local arrays, calls with the callee on
// the next line or the same one)
const entry = (name, depot, body) => `.visible .entry ${name}(\n\t.param .u64 ${name}_param_0\n)\n{\n` +
	(depot ? `\t.local .align 8 .b8 \t__local_depot0[${depot}];\n` : '') + `\t.reg .b64 \t%rd<9>;\n${body || ''}\tret;\n}\n`;
const func = (name, depot, body) => `.func  (.param .b64 func_retval0) ${name}(\n\t.param .b64 ${name}_param_0\n)\n{\n` +
	(depot ? `\t.local .align 8 .b8 \t__local_depot1[${depot}];\n` : '') + `${body || ''}\tret;\n}\n`;
const call = (callee) => `\t{ // callseq 0, 0\n\t.param .b64 param0;\n\t.param .b64 retval0;\n\tcall.uni (retval0), \n\t${callee}, \n\t(\n\tparam0\n\t);\n\t} // callseq 0\n`;
const head = '//\n// Generated by NVIDIA NVVM Compiler\n//\n.version 8.5\n.target sm_60\n.address_size 64\n\n\t// .globl\tk1\n';

console.log(`eegpu: ${TOOL}`);
{
	const P = scan(head + func('f2', 32, '') + func('f1', 128, call('f2')) + entry('k1', 64, call('f1')) + entry('k2', 512, ''));
	check('a call chain: bounded, the depots summed down the deepest chain', P.bounded === true && P.kernels === 2 && P.chains && P.chains.k1 === 224 && P.chains.k2 === 512 &&
		P.chainMax === 512 && P.chainKernel === 'k2', JSON.stringify(P));
}
{
	const P = scan(head + func('f2', 16, '') + func('f1', 64, call('f2') + call('f2')) + entry('k1', 8, call('f1') + `\tcall.uni f2, (param0);\n`));
	check('two calls of one callee, a callee on the call line: 8 + 64 + 16', P.bounded === true && P.chains && P.chains.k1 === 88, JSON.stringify(P));
}
{
	const P = scan(head + func('f1', 64, call('f1')) + entry('k1', 8, call('f1')));
	check('recursion: not bounded', P.bounded === false && /recursion/.test(P.why), JSON.stringify(P));
}
{
	// (f1 calls f2 before f2's body: a declaration first, as NVRTC writes one for a function used above its body)
	const decl = '.func  (.param .b64 func_retval0) f2(\n\t.param .b64 f2_param_0\n)\n;\n';
	const P = scan(head + decl + func('f1', 64, call('f2')) + func('f2', 32, call('f1')) + entry('k1', 8, call('f1')));
	check('mutual recursion (f1 -> f2 -> f1, f2 declared first): not bounded', P.bounded === false && /recursion/.test(P.why), JSON.stringify(P));
}
{
	const decl = '.func  (.param .b64 func_retval0) f2(\n\t.param .b64 f2_param_0\n)\n;\n';
	const P = scan(head + decl + func('f1', 64, call('f2')) + func('f2', 32, '') + entry('k1', 8, call('f1')));
	check('a declaration before its body: bounded, 8 + 64 + 32', P.bounded === true && P.chains && P.chains.k1 === 104, JSON.stringify(P));
}
{
	const ind = '\tprototype_0 : .callprototype (.param .b64 _) _ (.param .b64 _);\n\tcall (retval0), \n\t%rd4, \n\t(\n\tparam0\n\t)\n\t, prototype_0;\n';
	const P = scan(head + entry('k1', 8, ind));
	check('an indirect call (.callprototype, a register callee): not bounded', P.bounded === false && /indirect/.test(P.why), JSON.stringify(P));
}
{
	const P = scan(head + entry('k1', 8, `\tcall.uni (retval0), \n\t%rd3, \n\t(\n\tparam0\n\t);\n`));
	check('a register callee without a prototype line: not bounded', P.bounded === false && /indirect/.test(P.why), JSON.stringify(P));
}
{
	const P = scan(head + '.extern .func  (.param .b32 func_retval0) vprintf(\n\t.param .b64 vprintf_param_0\n)\n;\n' + entry('k1', 8, call('vprintf')));
	check('a callee with no body in the module (an extern): not bounded', P.bounded === false && /no body/.test(P.why), JSON.stringify(P));
}
{
	const P = scan(head + func('f1', 64, ''));
	check('a module without a kernel: not bounded', P.bounded === false, JSON.stringify(P));
}
// the real modules next to the tool
const mods = [8, 32, 128, 512].map((tw) => path.join(PTXDIR, `eegpu_${tw}.ptx`)).filter((f) => fs.existsSync(f));
for (const f of mods) {
	const tw = /eegpu_(\d+)\.ptx$/.exec(f)[1];
	const r = tool(['stackscan', f]);
	const P = r.lines[0] || {};
	const ex = P.chains ? P.chains[`exploreExpand_${tw}`] : undefined;
	check(`${path.basename(f)}: every kernel's stack bounded (no recursion, no indirect call)`, P.bounded === true && P.kernels >= 20 && ex > 0 && P.chainMax >= ex,
		`${P.kernels} kernels, the deepest depot chain ${P.chainMax} B (${P.chainKernel}), exploreExpand_${tw} ${ex} B, scan ${P.ms} ms${P.why ? `, ${P.why}` : ''}`);
}
if (!mods.length) console.log(`  (no eegpu_*.ptx in ${PTXDIR}: the real modules not checked)`);

if (args.gpu) {
	const ptxA = [`--ptxdir=${PTXDIR}`];
	const info = tool(['info', ...ptxA]);
	const I = info.lines[0] || {};
	if (!I.gpu) { console.log(`no GPU: ${I.why || info.err}`); process.exit(2); }
	const g = I.gpu, locals = Object.values(I.kernels || {}).map((k) => k.localBytes).filter((v) => v >= 0);
	const maxLocal = Math.max(...locals);
	check('info: the stack fitted to the kernels taken (covers every one, below main\'s 8 KB)', g.stackHow === 'fit' && g.stackBytes >= maxLocal && g.stackBytes < 8192 &&
		g.stackNow === g.stackBytes && g.ctxMB > 0, `stackBytes ${g.stackBytes} (${g.stackKernel}, largest local ${maxLocal}), stackNow ${g.stackNow}, ctxMB ${g.ctxMB} on ${g.name} (${g.sms} SMs)`);
	const infoM = tool(['info', ...ptxA], { EEAT_GPU_STACK: '8192' });
	const gm = (infoM.lines[0] || {}).gpu || {};
	check('EEAT_GPU_STACK=8192: main\'s fixed limit', gm.stackHow === 'env' && gm.stackBytes === 8192 && gm.stackNow >= 8192, `stackBytes ${gm.stackBytes}, stackNow ${gm.stackNow}, ctxMB ${gm.ctxMB}`);
	// the test room of test/gpulaunch.js: the same explore with the fit and with main's limit
	const W = 40, H = 16, cells = [];
	for (let x = 0; x < W; x++) cells.push([x, 0, 9], [x, H - 1, 9]);
	for (let y = 0; y < H; y++) cells.push([0, y, 9], [W - 1, y, 9]);
	for (const wx of [9, 17, 25]) cells.push([wx, 14, 9]);
	for (let x = 29; x <= 31; x++) cells.push([x, 10, 9]);
	cells.push([2, 14, 255], [38, 14, 121]);
	const level = E.prepareLevel(EL.toSimLevel(EL.readEelvl(ED.eelvlOf({ name: 'stack test', width: W, height: H, cells }))));
	const bin = path.join(TMP, 'level.bin'), reach = path.join(TMP, 'reach.bin');
	fs.writeFileSync(bin, G.levelBlob(level));
	RF.writeReachFile(RF.reachField(level), reach);
	const TIMING = new Set(['ticksPerSec', 'sec', 'seconds', 'gpu', 'launchMs', 't', 'launches', 'maxLaunchMs', 'maxLaunchKernel', 'maxKernelMs', 'maxKernelKernel',
		'gpuClock', 'busy', 'launchTarget', 'kernelLaunches', 'loadMs', 'allocMs', 'ctxMs', 'module', 'waitMs', 'launchTotalMs', 'kernelTotalMs', 'gapMs', 'wait', 'hostCpuMs', 'nice']);
	const norm = (o) => JSON.stringify(Object.fromEntries(Object.entries(o).filter(([k]) => !TIMING.has(k))));
	const ex = ['explore', bin, '-', '--finish=1', '--discrete=1', '--depth=1000', '--seconds=60', '--coarse=0', '--cqx=0.5', '--cqv=16', '--qy=1', '--qvy=16', `--reach=${reach}`, '--prune=1', ...ptxA];
	const a = tool(ex), b = tool(ex, { EEAT_GPU_STACK: '8192' });
	const pick = (r) => r.lines.filter((l) => l.ev !== 'progress' && l.ev !== 'ready' && l.ev !== 'closest').map(norm);
	const x = pick(a), y = pick(b), i = x.findIndex((l, k) => l !== y[k]);
	const da = a.lines.find((l) => l.ev === 'done') || {};
	check('explore: the same events with the fit as with EEAT_GPU_STACK=8192', a.code === 0 && b.code === 0 && x.length > 2 && x.length === y.length && i < 0,
		`${x.length} vs ${y.length} lines${i >= 0 ? `, first difference at ${i}: ${x[i]} / ${y[i]}` : ''}${a.code || b.code ? `, exit ${a.code} / ${b.code} ${a.err} ${b.err}` : ''}`);
	const ga = da.gpu || {};
	check('explore: no limit raised by the driver past the fit (stackNow = stackBytes after the search)', ga.stackHow === 'fit' && ga.stackNow === ga.stackBytes && /^exploreExpand_/.test(ga.stackKernel || ''),
		`stackBytes ${ga.stackBytes} (${ga.stackKernel}), stackNow ${ga.stackNow}, ctxMB ${ga.ctxMB}`);
	// a roll process takes only the roll kernels: its limit fits them (no job on stdin: the start event, then the end)
	const r = tool(['roll', bin, `--reach=${reach}`, '--rolls=8', '--roll=40', '--cap=65536', ...ptxA], {}, Buffer.alloc(0));
	const st = r.lines.find((l) => l.ev === 'start') || {};
	const gr = st.gpu || {};
	check('roll: its own kernels\' stack (less than explore\'s)', gr.stackHow === 'fit' && /^roll/.test(gr.stackKernel || '') && gr.stackBytes > 0 && gr.stackBytes < ga.stackBytes,
		`stackBytes ${gr.stackBytes} (${gr.stackKernel}), ctxMB ${gr.ctxMB} vs explore's ${ga.stackBytes} / ${ga.ctxMB}${r.code ? `, exit ${r.code} ${r.err}` : ''}`);
}
try { fs.rmSync(TMP, { recursive: true, force: true }); } catch (e) { /* */ }
console.log(`${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
